a=int(input('enter vlue a:'))
b=int(input('enter value b:'))
print('ADDTION OF TWO VALUES is:-',a+b)
print('SUBTRACTION OF TWO VALUES is:-',a-b)
print('MULTIPLICATION OF TWO VALUES is:-',a*b)
print('DIVISION OF TWO VALUES is:-',a/b)
print('MODULUS OF TWO VALUESA is:-',a%b)
